runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: templates/*
  upload: templates/*
  expiration: "15m"
  
- url: /js
  static_dir: js
  application_readable: true
  
- url: /css
  static_dir: css
  application_readable: true
  
- url: /.*
  script: blog.app

- url: /*
  script: blog.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
